@host = localhost
@port = 5000
@hostname = http://{{host}}:{{port}}

GET http://localhost:5000/

###

GET {{hostname}}/api/estoque

###

GET {{hostname}}/api/estoque/8

###

POST {{hostname}}/api/estoque
Content-Type: application/json

{
    "idProduto": 1,
    "quantidade": "40"
}

###